### ISSUE TITLE
Only 1 node discovered via CDP

### ISSUE THREAD

**Issue by ernanisf1984** [jasonbarbee/ansible-cisco-inventory#1]
Hello, read the documentation and upon running the program, only 1 node is discovered via CDP. Any ideas?

**Comment by jasonbarbee** [comment]
I'm sorry, this came in at a crazy time of life, and I dropped the ball and forgot. Got another issue today and saw this.
Can you provide any supplementary information? Models and versions? Any tracebacks?

**Comment by jasonbarbee** [comment]
Closing after no response received.
