### ISSUE TITLE
Cisco 3850 switch cdp neighbors not discovered.

### ISSUE THREAD

**Issue by AkliluET-Air** [jasonbarbee/ansible-cisco-inventory#2]
It works for mapping devices for me for a large network. But it stops on Cisco 3850. below is same of the error received. 

Written by Michael Laforest <mjlaforest@gmail.com>

     Config file: mnet.conf
       Root node: ##########
     Output file: /mnt/mycustomer.svg
     Crawl depth: 1
   Diagram title: MyCustomer
Out Catalog file: /mnt/mnet-discovered.csv

      +#################### (#########)
      >####################### (##########)
[E] get_snmp_bulk(!Qscvhu8): No SNMP response received before timeout
No CDP Neighbors Found.
Traceback (most recent call last):
  File "./mnet.py", line 198, in <module>
    main(sys.argv[1:])
  File "./mnet.py", line 67, in main
    graph(argv[1:])
  File "./mnet.py", line 129, in graph
    graph.crawl(opt_root_ip)
  File "/mnet/mnetsuite/graph.py", line 84, in crawl
    self._crawl_node(node, 0)
  File "/mnet/mnetsuite/graph.py", line 219, in _crawl_node
    neighbors = cdp_neighbors + lldp_neighbors
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

**Comment by jasonbarbee** [comment]
Thanks for the traceback. 
Interesting, it says no SNMP response, and therefore no neighbors found. 
Have you tried running it against the single 3850? Can you run snmpwalk against this 3850?

As a side note, that software called here is just Michael's MNET, which he changed the repo, and rebooted the project to Natlas. https://github.com/MJL85/natlas
You might want to see if his project works, as It looks like that's where the script failed. 
Let me know, I probably need to update this project.

**Comment by jasonbarbee** [comment]
Closing after no response for 5 months.
